CREATE TABLE household
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- "user" es palabra reservada en Postgres.
-- Una fila aquí es siempre una persona ya autenticada con Google: por eso google_sub es
-- NOT NULL. Lo que todavía no lo está vive en household_invitation.
CREATE TABLE users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_sub      VARCHAR(255) NOT NULL,
    -- email es lo que se muestra; email_canonical es la clave de comparación (alias de
    -- Gmail resueltos), y por eso un UNIQUE normal basta: no hace falta lower(email).
    email           VARCHAR(255) NOT NULL,
    email_canonical VARCHAR(255) NOT NULL,
    name            VARCHAR(120),
    avatar_url      VARCHAR(512),
    household_id    BIGINT       NOT NULL REFERENCES household (id),
    role            VARCHAR(16)  NOT NULL CHECK (role IN ('OWNER', 'MEMBER')),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ux_users_google_sub UNIQUE (google_sub),
    -- Una persona pertenece a una sola familia (MVP).
    CONSTRAINT ux_users_email_canonical UNIQUE (email_canonical)
);

CREATE INDEX ix_users_household ON users (household_id);

CREATE TABLE household_invitation
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id    BIGINT       NOT NULL REFERENCES household (id),
    email           VARCHAR(255) NOT NULL,
    email_canonical VARCHAR(255) NOT NULL,
    -- Solo un OWNER invita, y un OWNER no se puede quitar a sí mismo: la FK no queda huérfana.
    invited_by      BIGINT       NOT NULL REFERENCES users (id),
    status          VARCHAR(16)  NOT NULL
        CHECK (status IN ('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED')),
    expires_at      TIMESTAMPTZ  NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- Cuándo dejó de estar PENDING, sea por aceptación, revocación o caducidad.
    resolved_at     TIMESTAMPTZ
);

-- Índice único parcial: como mucho una invitación PENDING por email en todo el sistema, lo
-- que hace que aceptar sea inequívoco. No se puede expresar en JPA (ni en H2), así que vive
-- solo aquí; InvitationService lo comprueba antes de insertar.
CREATE UNIQUE INDEX ux_invitation_pending_email
    ON household_invitation (email_canonical) WHERE status = 'PENDING';

CREATE INDEX ix_invitation_household ON household_invitation (household_id);
